version: '3.9'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9100:9000"  # API
      - "9101:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    volumes:
      - minio-data:/data
    networks:
      - cloudapp_network

volumes:
  minio-data:

networks:
  cloudapp_network:
    external: true
